/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-11-17 05:27:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>글읽기</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>[글읽기]</h1> \r\n");
      out.write("\t<form action=\"update\" method=\"post\" name=\"frm\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"bno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<table border=1>\r\n");
      out.write("\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t<td width=100><b>Title</b></td>\r\n");
      out.write("\t\t\t\t<td width=300><input type=\"text\" name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=100><b>Content</b></td>\r\n");
      out.write("\t\t\t\t<td width=300><textarea rows=\"10\" cols=\"50\" name=\"content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=100><b>Writer</b></td>\r\n");
      out.write("\t\t\t\t<td width=300><input type=\"text\" name=\"Writer\" value=\"guest\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"수정\">\r\n");
      out.write("\t\t<input type=\"reset\" value=\"취소\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"삭제\" id=\"btnDelete\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"목록\" onClick=\"location.href='list'\">\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<h1>[첨부 파일 목록]</h1>\r\n");
      out.write("\t\t<div id=\"upload\">\r\n");
      out.write("\t\t\t<input type=\"file\" id=\"file\">\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<div id=\"uploaded\">\r\n");
      out.write("\t\t\t<ul id=\"uploadedFiles\"></ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar bno=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\tgetAttach()\r\n");
      out.write("\tfunction getAttach(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"getAttach.json\",\r\n");
      out.write("\t\t\tdata:{\"bno\":bno},\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t$(data).each(function(){\r\n");
      out.write("\t\t\t\t\tvar str=\"<li>\";\r\n");
      out.write("\t\t\t\t\tstr +=\"<img src=/displayFile?fileName=\" +this+ \" width=100 />\"\r\n");
      out.write("\t\t\t\t\tstr += \"<input type='text' name='files' value='\"+this+\"'>\";\r\n");
      out.write("\t\t\t\t\tstr += \" <a href='\"+this+\"'>삭제</a>\";\r\n");
      out.write("\t\t\t\t\tstr +=\"</li>\";\r\n");
      out.write("\t\t\t\t\t$(\"#uploadedFiles\").append(str);\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(frm).submit(function(e){\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tif($(frm.title).val()==\"\"){\r\n");
      out.write("\t\t\talert(\"제목을 입력하세요!\");\r\n");
      out.write("\t\t\t$(frm.title).focus();\r\n");
      out.write("\t\t}else if($(frm.contnet).val()==\"\"){\r\n");
      out.write("\t\t\talert(\"내용를 입력하세요!\");\r\n");
      out.write("\t\t\t$(frm.content).focus();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif(!confirm(\"게시글을 수정하시겠어요?\")) return;\r\n");
      out.write("\t\t\talert(\"수정되었습니다.\");\r\n");
      out.write("\t\t\tfrm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#btnDelete\").on(\"click\",function(){\r\n");
      out.write("\t\tif(!confirm(\"삭제하실래요?\")) return;\r\n");
      out.write("\t\tlocation.href=\"delete?bno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#file\").on(\"change\",function(){\r\n");
      out.write("\t\tvar file=$(\"#file\")[0].files[0]\r\n");
      out.write("\t\tif(file==null) return;\r\n");
      out.write("\t\tvar formData=new FormData();\r\n");
      out.write("\t\tformData.append(\"file\",file);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/uploadFile\",\r\n");
      out.write("\t\t\tprocessData:false,\r\n");
      out.write("\t\t\tcontentType:false,\r\n");
      out.write("\t\t\tdata:formData,\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tvar str=\"<li>\";\r\n");
      out.write("\t\t\t\tstr +=\"<img src=/displayFile?fileName=\" +data+ \" width=100 />\"\r\n");
      out.write("\t\t\t\tstr += \"<input type='text' name='files' value='\"+data+\"'>\";\r\n");
      out.write("\t\t\t\tstr += \" <a href='\"+data+\"'>삭제</a>\";\r\n");
      out.write("\t\t\t\tstr +=\"</li>\";\r\n");
      out.write("\t\t\t\t$(\"#uploadedFiles\").append(str);\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//업로드 파일 삭제\r\n");
      out.write("\t$(\"#uploadedFiles\").on(\"click\",\"a\",function(e){\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tvar fileName=$(this).attr(\"href\");\r\n");
      out.write("\t\tvar li=$(this).parent();\r\n");
      out.write("\t\tif(!confirm(\"삭제하시겠습니까?\")) return\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/deleteFile\",\r\n");
      out.write("\t\t\tdata:{\"fileName\":fileName},\r\n");
      out.write("\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\talert(\"삭제가 완료되었습니다.\")\r\n");
      out.write("\t\t\t\tli.remove();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
